kind: Namespace
apiVersion: v1
metadata:
  name: k8s-program
  labels:
    name: k8s-program
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: k8s-program
type: Opaque
data:
  username: dXNlcg==
  password: MTIzNDU=