apiVersion: v1
kind: ConfigMap
metadata:
  name: post-app-config
  labels:
    name: post-app-config
  namespace: {{ .Values.nameSpace }}
data:
  dburl: "jdbc:postgresql://post-db-service:5432/posts"
  userserviceurl: "http://user-app-service:8080/users/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-app
  labels:
    app: post-app
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    matchLabels:
      app: post-app
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 # how many pods we can add at a time
      maxUnavailable: 0  # maxUnavailable define how many pods can be unavailable during the rolling update
  template:
    metadata:
      labels:
        app: post-app
    spec:
      containers:
        - image: suleymanbolat/k8slearning:postservicewithtopic
          name: postservice
          ports:
            - containerPort: 8081
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            httpGet:
              scheme: HTTP
              path: /healthCheck
              port: 8081
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            httpGet:
              scheme: HTTP
              path: /healthCheck
              port: 8081
          volumeMounts:
            - name: db-credentials
              mountPath: "/etc/db-credentials"
              readOnly: true
          env:
            - name: dburl
              valueFrom:
                configMapKeyRef:
                  name: post-app-config
                  key: dburl
            - name: dbuser
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: dbpassword
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: userserviceurl
              valueFrom:
                configMapKeyRef:
                  name: post-app-config
                  key: userserviceurl
      volumes:
        - name: db-credentials
          secret:
            secretName: db-credentials




