apiVersion: v1
kind: Service
metadata:
  name: post-app-service
  labels:
    app: post-app-service
  namespace: {{ .Values.nameSpace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: post-app